name: fingerprints-daily
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas>=2.2
  - polars>=1.0
  - pyarrow>=16
  - pytorch>=2.2
  - python-dotenv>=1.0
  - requests>=2.31
  - lxml>=5
  - beautifulsoup4>=4.12
  - simplejson>=3.19
  - tqdm>=4.66
